config/routes.rb
Rails.application.routes.draw do
  #resources :players
  resources :teams do
    resources :players
  end

  get 'teams/index'
  # as :user do
  # 	put '/user/confirmation' => 'confirmations#update', 
  # 	:via => :patch, :as => :update_user_confirmation
  # end

  # devise_for :users, controllers: {
  # 	registrations: 'registrations',
  # 	confirmation: 'confirmations'

  # }

  #get "teams/edit" => 'teams#edit', :as => :edit

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "teams#index"

end

app/models/player.rb
class Player < ApplicationRecord
	belongs_to :team

  	mount_uploader :image, ImageUploader

  	validates_processing_of :image
	validate :image_size_validation
	 
	private
	  def image_size_validation
	    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
	  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_team
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  # GET /teams/:team_id/players
  def index
    @team = Team.find(params[:team_id]) # simplified, this will probably make use of strong params in your actual code
    @players = @team.players.page(params[:page]).per(3)
    #User.page(7).per(50)
    
    #binding.pry
    #@players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @team = Team.find(params[:team_id]) # simplified, this will probably make use of strong params in your actual code
    @players = @team.players
    #@player = Player.find(params[:id])
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
    render layout: false
    respond_to do |format|
      format.html
      # format.js 
    end
  end

  # POST /players
  # POST /players.json
  def create

    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to team_player_path(team_id: @player.team_id, id: @player.id), notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to team_player_path(team_id: @player.team_id, id: @player.id), notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy

    #@player = Player.find(params[:id])
    #@team = @player.post
    @player.destroy
    #binding.pry
    respond_to do |format|
      format.html { redirect_to team_players_path, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_team
      @team = Team.find(params[:team_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :description, :image, :team_id)
    end
end

############################
# def create
#     @article = Article.find(params[:article_id])

#     @comment = @article.comments.create(comment_params)
#     redirect_to article_path(@article)
#   end

#   def destroy
#     @article = Article.find(params[:article_id])

#     @comment = @article.comments.fincd(params[:id])

#     @comment.destroy
#     redirect_to article_path(@article)
#   end


#   private
#     def comment_params
#       params.require(:comment).permit(:commenter, :body)
#     end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<div class="container" style="background-color: red">
  <%= simple_form_for [@team, @player] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :image %>
      <%= f.association :team %>
    </div>

    <div class="form-actions">
      <%= f.button :submit , class: "btn btn-primary"%>
      <%= link_to 'Back', team_players_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', team: @team, player: @player %>

<%#= link_to 'Show', team_player_path([@team, @player]) %> 
<%#= link_to 'Back', team_players_path %>

app/views/players/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xl-8 mx-auto text-center">
      <div class="section-title">
        <h4> <%= @team.name %> </h4>
        <p><%= link_to 'Add New Player', new_team_player_path, class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>
  <div class="row top-buffer">
    <% @players.each do |player| %>
      <div class="col-md-4">
        <div class="single-team justify-content-center">
            <% if player.image %>
                <%= image_tag image_url(player.image), class: "rounded image-container" %>
            <% end %>
          <div class="team-hover">
            <h4><%= player.name %></h4>
          </div>
        </div>
        <div class="row justify-content-center">
          <%= link_to 'Show', team_player_path(team_id: player.team_id, id: player.id), class: "btn btn-info" %>
          <%= link_to 'Edit', edit_team_player_path(team_id: player.team_id, id: player.id), class: "btn btn-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>
<div class="justify-content-center">
  <%= paginate @players %>
</div>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', team: @team, player: @player %>

<%#= link_to 'Back', players_path %>

app/views/players/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="container portfolio">
	<div class="row">
		<div class="col-md-12">
			<div class="heading">				
				<%= link_to 'Edit', edit_team_player_path(team_id: @player.team_id, id: @player.id), class: "btn btn-primary" %> |


				<%= link_to 'Destroy', team_player_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %> |

				<%= link_to 'Back '.html_safe, team_players_path, class: "btn btn-info" %>

			</div>

		</div>	
	</div>
	<div class="bio-info">
		<div class="row">
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-12">
						<div class="bio-image">
							<% if @player.image %>
			                  <%= image_tag image_url(@player.image), class: "img-fluid" %>
			              <% end %>
						</div>		
					</div>

				</div>

			</div>

			<div class="col-md-6">
				<div class="bio-content">
					<p>
						<%= @player.name %>
					</p>
					<p>
					  <!-- <strong>Description:</strong> -->
					  <%= @player.description %>
					</p>

				</div>
			</div>
		</div>	
	</div>
</div>


<%#= link_to 'Edit', edit_team_player_path(team_id: @player.team_id, id: @player.id) %> |
<%#= link_to 'Destroy', team_player_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> |
<%#= link_to 'Back', team_players_path %>