config/routes.rb
Rails.application.routes.draw do
  #resources :players
  resources :teams do
    resources :players
  end

  get 'teams/index'
  # as :user do
  # 	put '/user/confirmation' => 'confirmations#update', 
  # 	:via => :patch, :as => :update_user_confirmation
  # end

  # devise_for :users, controllers: {
  # 	registrations: 'registrations',
  # 	confirmation: 'confirmations'

  # }

  #get "teams/edit" => 'teams#edit', :as => :edit

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "teams#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamMgmt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-success global-notification alert alert-success">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification alert alert-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to image_tag("ipllogo.jpeg", alt: "logo"), '/', class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav nav-fill w-100">
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="/teams">Home </a>
            </li>

            <li class="nav-item">
              <%= link_to 'Profile', edit_user_registration_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to 'New Team', new_team_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "Log Out", destroy_user_session_path, class: "nav-link", method: :delete %>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "navbar-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "navbar-item"%> 
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>